# Generated by Django 2.2.7 on 2019-11-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('messenger_id', models.IntegerField(choices=[(0, 'Viber'), (1, 'Telegram'), (2, 'WhatsApp')])),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='time of create')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='time of start')),
                ('message_status', models.IntegerField(blank=True, choices=[(0, 'Not sent'), (1, 'OK')], default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
